version: '3'

services:
  elasticsearch:
    image: strapdata/elassandra:latest
    container_name: elastic-scala
    environment:
      - node.name=es01
      - cluster.name=mobile-app-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
#      - "http.cors.allow-origin=*"
#      - "http.cors.enabled=true"
#      - "http.cors.allow-headers=X-Requested-With,X-Auth-Token,Content-Type,Content-Length,Authorization"
#      - "http.cors.allow-credentials=true"
#    ulimits:
#      memlock:
#        soft: -1
#        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
    networks:
      - esnet

  app:
    container_name: node-app
    restart: always
    build: ./
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3100
      - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - "3100:3100"
    volumes:
      - .:/app
      - ./error.log:/usr/src/app/error.log
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    networks:
      - esnet

volumes:
  esdata:
    driver: local

networks:
  esnet: