version: '3'

services:
  scala-api:
    image: registry.gitlab.com/scala1/scala-api:master
    expose:
      - "3000"
    environment:
      - VIRTUAL_HOST: api.scala-app.com
      - VIRTUAL_PORT: 3000
      - LETSENCRYPT_HOST: api.scala-app.com
    volumes:
      - /home/gitlab-runner/api:/app/data
    restart: unless-stopped