version: '3'

services:
  app:
    container_name: app
    restart: unless-stopped
    build: .
    environment:
      - PORT = 3100
    ports:
      - "3100:3100"
    links:
      - elasticsearch
  elasticsearch:
    container_name: elasticsearch
    image: strapdata/elassandra:latest
    ports:
      - "9201:9201"
