version: '2'
services:
  seed:
    container_name: elassandra
    image: "docker.io/strapdata/elassandra:6.8.4.4"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "DEBUG=true"
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m
    ports:
      - "9042:9042"
      - "9200:9200"
    volumes:
      - ./data:/var/lib/cassandra
  node:
    container_name: elassandra_node
    image: "docker.io/strapdata/elassandra:6.8.4.4"
    environment:
      - "JVM_OPTS=-Dcassandra.custom_query_handler_class=org.elassandra.index.ElasticQueryHandler"
      - "MAX_HEAP_SIZE=1200m"
      - "HEAP_NEWSIZE=300m"
      - "CASSANDRA_CGROUP_MEMORY_LIMIT=true"
      - "CASSANDRA_SEEDS=seed_node"
      - "DEBUG=true"
    links:
      - seed
    cap_add:
      - IPC_LOCK
    ulimits:
      memlock: -1
    mem_limit: 2000m

  kibana:
    container_name: kibana
    image: docker.elastic.co/kibana/kibana-oss:6.8.4
    environment:
      - "ELASTICSEARCH_URL=http://elassandra:9200"
    ports:
      - "5601:5601"
    mem_limit: 500m

  nodejs:
    container_name: nodejs
    restart: always
    build: ./
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3100
      - "ELASTICSEARCH_URL=http://elassandra:9200"
    ports:
      - "3100:3100"
    volumes:
      - ./app:/app
      - ./error.log:/usr/src/app/error.log
    links:
      - seed

volumes:
  esdata:
    driver: local
