version: '3'

services:
  elasticsearch:
    image: strapdata/elassandra:latest
    container_name: elastic-scala
    environment:
      - node.name=es01
      - cluster.name=mobile-app-cluster
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - esnet

  app:
    container_name: node-app
    restart: always
    build: ./
    environment:
      - NODE_ENV=local
      - ES_HOST=elasticsearch
      - NODE_PORT=3100
      - ELASTIC_URL=http://elasticsearch:9200
    ports:
      - "3100:3100"
    volumes:
      - .:/app
      - ./error.log:/usr/src/app/error.log
    depends_on:
      - elasticsearch
    links:
      - elasticsearch:elasticsearch
    networks:
      - esnet

  runner-ts:
    build: runner-ts/.

  runner-deploy:
    build: runner-deploy/.
    volumes:
      - staging:/www-staging
      - production:/www-production

  staging:
    image: 'nginx'
    ports:
      - '3111:80'
    volumes:
      - staging:/usr/share/nginx/html

  production:
    image: 'nginx'
    ports:
      - '3100:80'
    volumes:
      - production:/usr/share/nginx/html

volumes:
  esdata:
    driver: local
  staging:
  production:

networks:
  esnet:
