import { ELASTIC_CLIENT } from "../utils/elasticsearch";
import {excelToJsonService} from "./excelToJson.service";
import {ProductsController} from "../controllers/products/products";
import {Request} from "express";
import {Product} from "../models/Product";
import {Criteria} from "../models/Criteria";

export class bulkindexService {
    private static instance: bulkindexService;

    public static getInstance(): bulkindexService {
        if(!bulkindexService.instance) {
            bulkindexService.instance = new bulkindexService();
        }
        return bulkindexService.instance;
    }

    /*public loop_index() {
        const data = excelToJsonService.getInstance().processXlsxToJson();
        var product : Product ;

        for (var i=0; i < Object.keys(data).length; i++) {
            const criteria : Map<String, String> = new Map<String, String>([
                ['Portfolio Date', data[i]['Portfolio Date']],
                ['KIID Ongoing Charge', data[i]['KIID Ongoing Charge']],
                ['Sustainability Rating Date', data[i]['Sustainability Rating Date']],
                ['Morningstar Sustainability Rating', data[i]['Morningstar Sustainability Rating']],
                ['Historical Sustainability Score', data[i]['Historical Sustainability Score']],
                ['Portfolio Sustainability Score', data[i]['Portfolio Sustainability Score']],
                ['Sustainability Percent Rank in Global Category', data[i]['Sustainability Percent Rank in Global Category']],
                ['Sustainability Absolute Rank in Global Category', data[i]['Sustainability Absolute Rank in Global Category']],
                ['Environmental Risk Score vs. Global Category', data[i]['Environmental Risk Score vs. Global Category']],
                ['Portfolio Environmental Score', data[i]['Portfolio Environmental Score']],
                ['Environmental Risk Percent Rank in Global Category', data[i]['Environmental Risk Percent Rank in Global Category']],
                ['Environmental Risk Absolute Rank in Global Category', data[i]['Environmental Risk Absolute Rank in Global Category']],
                ['Social Risk Score vs. Global Category', data[i]['Social Risk Score vs. Global Category']],
                ['Portfolio Social Score', data[i]['Portfolio Social Score']],
                ['Social Risk Percent Rank in Global Category', data[i]['Social Risk Percent Rank in Global Category']],
                ['Social Risk Absolute Rank in Global Category', data[i]['Social Risk Absolute Rank in Global Category']],
                ['Governance Risk Score vs. Global Category', data[i]['Governance Risk Score vs. Global Category']],
                ['Portfolio Governance Score', data[i]['Portfolio Governance Score']],
                ['Governance Risk Percent Rank in Global Category', data[i]['Governance Risk Percent Rank in Global Category']],
                ['Governance Risk Absolute Rank in Global Category', data[i]['Governance Risk Absolute Rank in Global Category']],
                ['Percent of AUM Covered - ESG', data[i]['Percent of AUM Covered - ESG']],
                ['Number of Securities Scored - ESG', data[i]['Number of Securities Scored - ESG']],
                ['Number of Securities Not Scored - ESG', data[i]['Number of Securities Not Scored - ESG']],
                ['Percent of AUM Covered - Controversy', data[i]['Percent of AUM Covered - Controversy']],
                ['Number of Securities Scored - Controversy', data[i]['Number of Securities Scored - Controversy']],
                ['Number of Securities Not Scored - Controversy', data[i]['Number of Securities Not Scored - Controversy']],
                ['Percent of AUM with Negligible ESG Risk Scores', data[i]['Percent of AUM with Negligible ESG Risk Scores']],
                ['Percent of AUM with Low ESG Risk Scores', data[i]['Percent of AUM with Low ESG Risk Scores']],
                ['Percent of AUM with Medium ESG Risk Scores', data[i]['Percent of AUM with Medium ESG Risk Scores']],
                ['Percent of AUM with High ESG Risk Scores', data[i]['Percent of AUM with High ESG Risk Scores']],
                ['Percent of AUM with Severe ESG Risk Scores', data[i]['Percent of AUM with Severe ESG Risk Scores']],
                ['Sustainability Global Category Average', data[i]['Sustainability Global Category Average']],
                ['Environmental Global Category Average', data[i]['Environmental Global Category Average']],
                ['Social Global Category Average', data[i]['Social Global Category Average']],
                ['Governance Global Category Average', data[i]['Governance Global Category Average']],
                ['Product Involvement % - Adult Entertainment', data[i]['Product Involvement % - Adult Entertainment']],
                ['Product Involvement # of Holdings - Adult Entertainment', data[i]['Product Involvement # of Holdings - Adult Entertainment']],
                ['Product Involvement Cat Avg % - Adult Entertainment', data[i]['Product Involvement Cat Avg % - Adult Entertainment']],
                ['Product Involvement % - Alcohol', data[i]['Product Involvement % - Alcohol']],
                ['Product Involvement # of Holdings - Alcohol', data[i]['Product Involvement # of Holdings - Alcohol']],
                ['Product Involvement Cat Avg % - Alcohol', data[i]['Product Involvement Cat Avg % - Alcohol']],
                ['Product Involvement % - Animal Testing', data[i]['Product Involvement % - Animal Testing']],
                ['Product Involvement # of Holdings - Animal Testing', data[i]['Product Involvement # of Holdings - Animal Testing']],
                ['Product Involvement Cat Avg % - Animal Testing', data[i]['Product Involvement Cat Avg % - Animal Testing']],
                ['Product Involvement % - Abortive/Contraceptives/Stem Cell', data[i]['Product Involvement % - Abortive/Contraceptives/Stem Cell']],
                ['Product Involvement # of Holdings - Abortive/Contraceptives/Stem Cell', data[i]['Product Involvement # of Holdings - Abortive/Contraceptives/Stem Cell']],
                ['Product Involvement Cat Avg % - Abortive/Contraceptives/Stem Cell', data[i]['Product Involvement Cat Avg % - Abortive/Contraceptives/Stem Cell']],
                ['Product Involvement % - Controversial Weapons', data[i]['Product Involvement % - Controversial Weapons']],
                ['Product Involvement # of Holdings - Controversial Weapons', data[i]['Product Involvement # of Holdings - Controversial Weapons']],
                ['Product Involvement Cat Avg % - Controversial Weapons', data[i]['Product Involvement Cat Avg % - Controversial Weapons']],
                ['Product Involvement % - Fur & Specialty Leather', data[i]['Product Involvement % - Fur & Specialty Leather']],
                ['Product Involvement # of Holdings - Fur & Specialty Leather', data[i]['Product Involvement # of Holdings - Fur & Specialty Leather']],
                ['Product Involvement Cat Avg % - Fur & Specialty Leather', data[i]['Product Involvement Cat Avg % - Fur & Specialty Leather']],
                ['Product Involvement % - Gambling', data[i]['Product Involvement % - Gambling']],
                ['Product Involvement # of Holdings - Gambling', data[i]['Product Involvement # of Holdings - Gambling']],
                ['Product Involvement Cat Avg % - Gambling', data[i]['Product Involvement Cat Avg % - Gambling']],
                ['Product Involvement % - GMO', data[i]['Product Involvement % - GMO']],
                ['Product Involvement # of Holdings - GMO', data[i]['Product Involvement # of Holdings - GMO']],
                ['Product Involvement Cat Avg % - GMO', data[i]['Product Involvement Cat Avg % - GMO']],
                ['Product Involvement % - Military Contracting', data[i]['Product Involvement % - Military Contracting']],
                ['Product Involvement # of Holdings - Military Contracting', data[i]['Product Involvement # of Holdings - Military Contracting']],
                ['Product Involvement Cat Avg % - Military Contracting', data[i]['Product Involvement Cat Avg % - Military Contracting']],
                ['Product Involvement % - Nuclear', data[i]['Product Involvement % - Nuclear']],
                ['Product Involvement # of Holdings - Nuclear', data[i]['Product Involvement # of Holdings - Nuclear']],
                ['Product Involvement Cat Avg % - Nuclear', data[i]['Product Involvement Cat Avg % - Nuclear']],
                ['Product Involvement % - Palm Oil', data[i]['Product Involvement % - Palm Oil']],
                ['Product Involvement # of Holdings - Palm Oil', data[i]['Product Involvement # of Holdings - Palm Oil']],
                ['Product Involvement Cat Avg % - Palm Oil', data[i]['Product Involvement Cat Avg % - Palm Oil']],
                ['Product Involvement % - Pesticides', data[i]['Product Involvement % - Pesticides']],
                ['Product Involvement # of Holdings - Pesticides', data[i]['Product Involvement # of Holdings - Pesticides']],
                ['Product Involvement Cat Avg % - Pesticides', data[i]['Product Involvement Cat Avg % - Pesticides']],
                ['Product Involvement % - Small Arms', data[i]['Product Involvement % - Small Arms']],
                ['Product Involvement # of Holdings - Small Arms', data[i]['Product Involvement # of Holdings - Small Arms']],
                ['Product Involvement Cat Avg % - Small Arms', data[i]['Product Involvement Cat Avg % - Small Arms']],
                ['Product Involvement % - Thermal Coal', data[i]['Product Involvement % - Thermal Coal']],
                ['Product Involvement # of Holdings - Thermal Coal', data[i]['Product Involvement # of Holdings - Thermal Coal']],
                ['Product Involvement Cat Avg % - Thermal Coal', data[i]['Product Involvement Cat Avg % - Thermal Coal']],
                ['Product Involvement % - Tobacco', data[i]['Product Involvement % - Tobacco']],
                ['Product Involvement # of Holdings - Tobacco', data[i]['Product Involvement # of Holdings - Tobacco']],
                ['Product Involvement Cat Avg % - Tobacco', data[i]['Product Involvement Cat Avg % - Tobacco']],
                ['Carbon Date', data[i]['Carbon Date']],
                ['Percent AUM Covered - Carbon', data[i]['Percent AUM Covered - Carbon']],
                ['Low Carbon Designation', data[i]['Low Carbon Designation']],
                ['Carbon Risk Score', data[i]['Carbon Risk Score']],
                ['Carbon Risk Score Percent Rank in Category', data[i]['Carbon Risk Score Percent Rank in Category']],
                ['Carbon Risk Score Category Average', data[i]['Carbon Risk Score Category Average']],
                ['Benchmark Carbon Risk Score', data[i]['Benchmark Carbon Risk Score']],
                ['12 Month Average Carbon Risk Score', data[i]['12 Month Average Carbon Risk Score']],
                ['12 Month Average Carbon Risk Category Average', data[i]['12 Month Average Carbon Risk Category Average']],
                ['12 Month Average Carbon Risk Percent Rank in Category', data[i]['12 Month Average Carbon Risk Percent Rank in Category']],
                ['Carbon Exposure Score', data[i]['Carbon Exposure Score']],
                ['Carbon Exposure Score Category Average', data[i]['Carbon Exposure Score Category Average']],
                ['Carbon Management Score', data[i]['Carbon Management Score']],
                ['Carbon Management Score Category Average', data[i]['Carbon Management Score Category Average']],
                ['Carbon Operations Risk', data[i]['Carbon Operations Risk']],
                ['Carbon Operations Risk Category Average', data[i]['Carbon Operations Risk Category Average']],
                ['Carbon Products & Services Risk', data[i]['Carbon Products & Services Risk']],
                ['Carbon Products & Services Risk Category Average', data[i]['Carbon Products & Services Risk Category Average']],
                ['Stranded Assets Risk', data[i]['Stranded Assets Risk']],
                ['Stranded Assets Risk Category Average', data[i]['Stranded Assets Risk Category Average']],
                ['Carbon Intensity', data[i]['Carbon Intensity']],
                ['Carbon Intensity Category Average', data[i]['Carbon Intensity Category Average']],
                ['Fossil Fuel Involvement', data[i]['Fossil Fuel Involvement']],
                ['12 Month Average Fossil Fuel Exposure', data[i]['12 Month Average Fossil Fuel Exposure']],
                ['Fossil Fuel Category Average', data[i]['Fossil Fuel Category Average']],
                ['Thermal Coal Power Generation Involvement', data[i]['Thermal Coal Power Generation Involvement']],
                ['Thermal Coal Power Generation Category Average', data[i]['Thermal Coal Power Generation Category Average']],
                ['Thermal Coal Extraction Involvement', data[i]['Thermal Coal Extraction Involvement']],
                ['Thermal Coal Extraction Category Average', data[i]['Thermal Coal Extraction Category Average']],
                ['Oil Sands Extraction Involvement', data[i]['Oil Sands Extraction Involvement']],
                ['Oil Sands Extraction Category Average', data[i]['Oil Sands Extraction Category Average']],
                ['Arctic Oil & Gas Exploration Involvement', data[i]['Arctic Oil & Gas Exploration Involvement']],
                ['Arctic Oil & Gas Exploration Category Average', data[i]['Arctic Oil & Gas Exploration Category Average']],
                ['Carbon Solutions Involvement', data[i]['Carbon Solutions Involvement']],
                ['Carbon Solutions Category Average', data[i]['Carbon Solutions Category Average']],
                ['Renewable Energy Production Involvement', data[i]['Renewable Energy Production Involvement']],
                ['Renewable Energy Production Category Average', data[i]['Renewable Energy Production Category Average']],
                ['Renewable Energy Supporting Products & Services Involvement', data[i]['Renewable Energy Supporting Products & Services Involvement']],
                ['Renewable Energy Supporting Products & Services Category Average', data[i]['Renewable Energy Supporting Products & Services Category Average']],
                ['Green Transportation Involvement', data[i]['Green Transportation Involvement']],
                ['Green Transportation Category Average', data[i]['Green Transportation Category Average']],
                ['Oil & Gas Generation Involvement', data[i]['Oil & Gas Generation Involvement']],
                ['Oil & Gas Generation Category Average', data[i]['Oil & Gas Generation Category Average']],
                ['Oil & Gas Production Involvement', data[i]['Oil & Gas Production Involvement']],
                ['Oil & Gas Production Category Average', data[i]['Oil & Gas Production Category Average']],
                ['Oil & Gas Products & Service Involvement', data[i]['Oil & Gas Products & Service Involvement']],
                ['Oil & Gas Products & Services Category Average', data[i]['Oil & Gas Products & Services Category Average']],
                ['Carbon Risk Score All Funds Rank', data[i]['Carbon Risk Score All Funds Rank']],
                ['Carbon Risk Classification', data[i]['Carbon Risk Classification']],
                ['Percent of AUM with Negligible Carbon Risk', data[i]['Percent of AUM with Negligible Carbon Risk']],
                ['Percent of AUM with Low Carbon Risk', data[i]['Percent of AUM with Low Carbon Risk']],
                ['Percent of AUM with Medium Carbon Risk', data[i]['Percent of AUM with Medium Carbon Risk']],
                ['Percent of AUM with High Carbon Risk', data[i]['Percent of AUM with High Carbon Risk']],
                ['Percent of AUM with Severe Carbon Risk', data[i]['Percent of AUM with Severe Carbon Risk']],
                ['Carbon Exposure Score Percent Rank in Category', data[i]['Carbon Exposure Score Percent Rank in Category']],
                ['Carbon Management Score Percent Rank in Category', data[i]['Carbon Management Score Percent Rank in Category']],
                ['Carbon Operations Risk Percent Rank in Category', data[i]['Carbon Operations Risk Percent Rank in Category']],
                ['Carbon Products & Services Risk Percent Rank in Category', data[i]['Carbon Products & Services Risk Percent Rank in Category']],
                ['Stranded Assets Risk Percent Rank in Category', data[i]['Stranded Assets Risk Percent Rank in Category']],
                ['Carbon Intensity Percent Rank in Category', data[i]['Carbon Intensity Percent Rank in Category']],
                ['Highest Carbon Risk Score Category', data[i]['Highest Carbon Risk Score Category']],
                ['Lowest Carbon Risk Score Category', data[i]['Lowest Carbon Risk Score Category']],
                ['Highest Fossil Fuel Category', data[i]['Highest Fossil Fuel Category']],
                ['Lowest Fossil Fuel Category', data[i]['Lowest Fossil Fuel Category']],
                ['12 Month Average Fossil Fuel Category Average', data[i]['12 Month Average Fossil Fuel Category Average']],
                ['12 Month Average Highest Carbon Risk Score Category', data[i]['12 Month Average Highest Carbon Risk Score Category']],
                ['12 Month Average Lowest Carbon Risk Score Category', data[i]['12 Month Average Lowest Carbon Risk Score Category']],
                ['12 Month Average Highest Fossil Fuel Involvement Category', data[i]['12 Month Average Highest Fossil Fuel Involvement Category']],
                ['12 Month Average Lowest Fossil Fuel Involvement Category', data[i]['12 Month Average Lowest Fossil Fuel Involvement Category']],
                ['Sustainable Investment - Overall', data[i]['Sustainable Investment - Overall']],
                ['Sustainable Investment - ESG Fund Overall', data[i]['Sustainable Investment - ESG Fund Overall']],
                ['Sustainable Investment - ESG Incorporation', data[i]['Sustainable Investment - ESG Incorporation']],
                ['Sustainable Investment - ESG Engagement', data[i]['Sustainable Investment - ESG Engagement']],
                ['Sustainable Investment - Impact Fund Overall', data[i]['Sustainable Investment - Impact Fund Overall']],
                ['Sustainable Investment - Gender & Diversity', data[i]['Sustainable Investment - Gender & Diversity']],
                ['Sustainable Investment - Low Carbon/Fossil-Fuel Free', data[i]['Sustainable Investment - Low Carbon/Fossil-Fuel Free']],
                ['Sustainable Investment - Community Development', data[i]['Sustainable Investment - Community Development']],
                ['Sustainable Investment - Environmental', data[i]['Sustainable Investment - Environmental']],
                ['Sustainable Investment - Other Impact Themes', data[i]['Sustainable Investment - Other Impact Themes']],
                ['Sustainable Investment - Environmental Sector Overall', data[i]['Sustainable Investment - Environmental Sector Overall']],
                ['Sustainable Investment - Renewable Energy', data[i]['Sustainable Investment - Renewable Energy']],
                ['Sustainable Investment - Water-Focused', data[i]['Sustainable Investment - Water-Focused']],
                ['Sustainable Investment - General Environmental Sector', data[i]['Sustainable Investment - General Environmental Sector']],
                ['Employs Exclusions - Overall', data[i]['Employs Exclusions - Overall']],
                ['Employs Exclusions - Uses Norms-Based Screening', data[i]['Employs Exclusions - Uses Norms-Based Screening']],
                ['Employs Exclusions - Abortion/Stem Cells', data[i]['Employs Exclusions - Abortion/Stem Cells']],
                ['Employs Exclusions - Adult Entertainment', data[i]['Employs Exclusions - Adult Entertainment']],
                ['Employs Exclusions - Alcohol', data[i]['Employs Exclusions - Alcohol']],
                ['Employs Exclusions - Animal Testing', data[i]['Employs Exclusions - Animal Testing']],
                ['Employs Exclusions - Controversial Weapons', data[i]['Employs Exclusions - Controversial Weapons']],
                ['Employs Exclusions - Fur & Specialty Leather', data[i]['Employs Exclusions - Fur & Specialty Leather']],
                ['Employs Exclusions - Gambling', data[i]['Employs Exclusions - Gambling']],
                ['Employs Exclusions - GMOs', data[i]['Employs Exclusions - GMOs']],
                ['Employs Exclusions - Military Contracting', data[i]['Employs Exclusions - Military Contracting']],
                ['Employs Exclusions - Nuclear', data[i]['Employs Exclusions - Nuclear']],
                ['Employs Exclusions - Palm Oil', data[i]['Employs Exclusions - Palm Oil']],
                ['Employs Exclusions - Pesticides', data[i]['Employs Exclusions - Pesticides']],
                ['Employs Exclusions - Small Arms', data[i]['Employs Exclusions - Small Arms']],
                ['Employs Exclusions - Thermal Coal', data[i]['Employs Exclusions - Thermal Coal']],
                ['Employs Exclusions - Tobacco', data[i]['Employs Exclusions - Tobacco']],
                ['Employs Exclusions - Other', data[i]['Employs Exclusions - Other']],
                ['Historical Sustainability Score Global Category Average', data[i]['Historical Sustainability Score Global Category Average']],
                ['Historical Sustainability Percent Rank in Global Category', data[i]['Historical Sustainability Percent Rank in Global Category']],
                ['Historical Sustainability Absolute Rank in Global Category', data[i]['Historical Sustainability Absolute Rank in Global Category']],
                ['Portfolio ESG Risk Exposure Score', data[i]['Portfolio ESG Risk Exposure Score']],
                ['Portfolio ESG Managed Risk Score', data[i]['Portfolio ESG Managed Risk Score']],
                ['Percent of AUM with NULL ESG Risk Scores', data[i]['Percent of AUM with NULL ESG Risk Scores']],
                ['Percent of AUM with High & Severe Controversies', data[i]['Percent of AUM with High & Severe Controversies']],
                ['Percent of AUM with No Controversies', data[i]['Percent of AUM with No Controversies']],
                ['Percent of AUM with Low Controveries', data[i]['Percent of AUM with Low Controveries']],
                ['Percent of AUM with Moderate Controversies', data[i]['Percent of AUM with Moderate Controversies']],
                ['Percent of AUM with Significant Controversies', data[i]['Percent of AUM with Significant Controversies']],
                ['Percent of AUM with High Controversies', data[i]['Percent of AUM with High Controversies']],
                ['Percent of AUM with Severe Controversies', data[i]['Percent of AUM with Severe Controversies']]
            ]);
            product = new  Product('unknown', data[i]["Name"], data[i]["Global Category"], criteria);
            ELASTIC_CLIENT.index({
                index: 'scala',
                type: 'database',
                body : {
                    "type": "product",
                    "isin_code": product.isin_code,
                    "name": product.name,
                    "category": product.category,
                    "criteria": product.criteria
                }
            }, (err, response) => {
                if (err)
                    console.log(err);
                else
                    console.log(response)
            })
        }
    }*/

    mapToObj = m => {
        return Array.from(m).reduce((obj, [key, value]) => {
            obj[key] = value;
            return obj;
        }, {});
    };

    toJson = m => {
        return JSON.stringify(Array.from(m.entries()))
    };

    public bulk(): void {

        const data = excelToJsonService.getInstance().processXlsxToJson();
        var products_list = [];
        //Object.keys(data).length
        for (var i=0; i < Object.keys(data).length; i++) {
            const criteria : Map<String, String> = new Map<String, String>([
                ['Portfolio Date', data[i]['Portfolio Date']],
                ['KIID Ongoing Charge', data[i]['KIID Ongoing Charge']],
                ['Sustainability Rating Date', data[i]['Sustainability Rating Date']],
                ['Morningstar Sustainability Rating', data[i]['Morningstar Sustainability Rating']],
                ['Historical Sustainability Score', data[i]['Historical Sustainability Score']],
                ['Portfolio Sustainability Score', data[i]['Portfolio Sustainability Score']],
                ['Sustainability Percent Rank in Global Category', data[i]['Sustainability Percent Rank in Global Category']],
                ['Sustainability Absolute Rank in Global Category', data[i]['Sustainability Absolute Rank in Global Category']],
                ['Environmental Risk Score vs. Global Category', data[i]['Environmental Risk Score vs. Global Category']],
                ['Portfolio Environmental Score', data[i]['Portfolio Environmental Score']],
                ['Environmental Risk Percent Rank in Global Category', data[i]['Environmental Risk Percent Rank in Global Category']],
                ['Environmental Risk Absolute Rank in Global Category', data[i]['Environmental Risk Absolute Rank in Global Category']],
                ['Social Risk Score vs. Global Category', data[i]['Social Risk Score vs. Global Category']],
                ['Portfolio Social Score', data[i]['Portfolio Social Score']],
                ['Social Risk Percent Rank in Global Category', data[i]['Social Risk Percent Rank in Global Category']],
                ['Social Risk Absolute Rank in Global Category', data[i]['Social Risk Absolute Rank in Global Category']],
                ['Governance Risk Score vs. Global Category', data[i]['Governance Risk Score vs. Global Category']],
                ['Portfolio Governance Score', data[i]['Portfolio Governance Score']],
                ['Governance Risk Percent Rank in Global Category', data[i]['Governance Risk Percent Rank in Global Category']],
                ['Governance Risk Absolute Rank in Global Category', data[i]['Governance Risk Absolute Rank in Global Category']],
                ['Percent of AUM Covered - ESG', data[i]['Percent of AUM Covered - ESG']],
                ['Number of Securities Scored - ESG', data[i]['Number of Securities Scored - ESG']],
                ['Number of Securities Not Scored - ESG', data[i]['Number of Securities Not Scored - ESG']],
                ['Percent of AUM Covered - Controversy', data[i]['Percent of AUM Covered - Controversy']],
                ['Number of Securities Scored - Controversy', data[i]['Number of Securities Scored - Controversy']],
                ['Number of Securities Not Scored - Controversy', data[i]['Number of Securities Not Scored - Controversy']],
                ['Percent of AUM with Negligible ESG Risk Scores', data[i]['Percent of AUM with Negligible ESG Risk Scores']],
                ['Percent of AUM with Low ESG Risk Scores', data[i]['Percent of AUM with Low ESG Risk Scores']],
                ['Percent of AUM with Medium ESG Risk Scores', data[i]['Percent of AUM with Medium ESG Risk Scores']],
                ['Percent of AUM with High ESG Risk Scores', data[i]['Percent of AUM with High ESG Risk Scores']],
                ['Percent of AUM with Severe ESG Risk Scores', data[i]['Percent of AUM with Severe ESG Risk Scores']],
                ['Sustainability Global Category Average', data[i]['Sustainability Global Category Average']],
                ['Environmental Global Category Average', data[i]['Environmental Global Category Average']],
                ['Social Global Category Average', data[i]['Social Global Category Average']],
                ['Governance Global Category Average', data[i]['Governance Global Category Average']],
                ['Product Involvement % - Adult Entertainment', data[i]['Product Involvement % - Adult Entertainment']],
                ['Product Involvement # of Holdings - Adult Entertainment', data[i]['Product Involvement # of Holdings - Adult Entertainment']],
                ['Product Involvement Cat Avg % - Adult Entertainment', data[i]['Product Involvement Cat Avg % - Adult Entertainment']],
                ['Product Involvement % - Alcohol', data[i]['Product Involvement % - Alcohol']],
                ['Product Involvement # of Holdings - Alcohol', data[i]['Product Involvement # of Holdings - Alcohol']],
                ['Product Involvement Cat Avg % - Alcohol', data[i]['Product Involvement Cat Avg % - Alcohol']],
                ['Product Involvement % - Animal Testing', data[i]['Product Involvement % - Animal Testing']],
                ['Product Involvement # of Holdings - Animal Testing', data[i]['Product Involvement # of Holdings - Animal Testing']],
                ['Product Involvement Cat Avg % - Animal Testing', data[i]['Product Involvement Cat Avg % - Animal Testing']],
                ['Product Involvement % - Abortive/Contraceptives/Stem Cell', data[i]['Product Involvement % - Abortive/Contraceptives/Stem Cell']],
                ['Product Involvement # of Holdings - Abortive/Contraceptives/Stem Cell', data[i]['Product Involvement # of Holdings - Abortive/Contraceptives/Stem Cell']],
                ['Product Involvement Cat Avg % - Abortive/Contraceptives/Stem Cell', data[i]['Product Involvement Cat Avg % - Abortive/Contraceptives/Stem Cell']],
                ['Product Involvement % - Controversial Weapons', data[i]['Product Involvement % - Controversial Weapons']],
                ['Product Involvement # of Holdings - Controversial Weapons', data[i]['Product Involvement # of Holdings - Controversial Weapons']],
                ['Product Involvement Cat Avg % - Controversial Weapons', data[i]['Product Involvement Cat Avg % - Controversial Weapons']],
                ['Product Involvement % - Fur & Specialty Leather', data[i]['Product Involvement % - Fur & Specialty Leather']],
                ['Product Involvement # of Holdings - Fur & Specialty Leather', data[i]['Product Involvement # of Holdings - Fur & Specialty Leather']],
                ['Product Involvement Cat Avg % - Fur & Specialty Leather', data[i]['Product Involvement Cat Avg % - Fur & Specialty Leather']],
                ['Product Involvement % - Gambling', data[i]['Product Involvement % - Gambling']],
                ['Product Involvement # of Holdings - Gambling', data[i]['Product Involvement # of Holdings - Gambling']],
                ['Product Involvement Cat Avg % - Gambling', data[i]['Product Involvement Cat Avg % - Gambling']],
                ['Product Involvement % - GMO', data[i]['Product Involvement % - GMO']],
                ['Product Involvement # of Holdings - GMO', data[i]['Product Involvement # of Holdings - GMO']],
                ['Product Involvement Cat Avg % - GMO', data[i]['Product Involvement Cat Avg % - GMO']],
                ['Product Involvement % - Military Contracting', data[i]['Product Involvement % - Military Contracting']],
                ['Product Involvement # of Holdings - Military Contracting', data[i]['Product Involvement # of Holdings - Military Contracting']],
                ['Product Involvement Cat Avg % - Military Contracting', data[i]['Product Involvement Cat Avg % - Military Contracting']],
                ['Product Involvement % - Nuclear', data[i]['Product Involvement % - Nuclear']],
                ['Product Involvement # of Holdings - Nuclear', data[i]['Product Involvement # of Holdings - Nuclear']],
                ['Product Involvement Cat Avg % - Nuclear', data[i]['Product Involvement Cat Avg % - Nuclear']],
                ['Product Involvement % - Palm Oil', data[i]['Product Involvement % - Palm Oil']],
                ['Product Involvement # of Holdings - Palm Oil', data[i]['Product Involvement # of Holdings - Palm Oil']],
                ['Product Involvement Cat Avg % - Palm Oil', data[i]['Product Involvement Cat Avg % - Palm Oil']],
                ['Product Involvement % - Pesticides', data[i]['Product Involvement % - Pesticides']],
                ['Product Involvement # of Holdings - Pesticides', data[i]['Product Involvement # of Holdings - Pesticides']],
                ['Product Involvement Cat Avg % - Pesticides', data[i]['Product Involvement Cat Avg % - Pesticides']],
                ['Product Involvement % - Small Arms', data[i]['Product Involvement % - Small Arms']],
                ['Product Involvement # of Holdings - Small Arms', data[i]['Product Involvement # of Holdings - Small Arms']],
                ['Product Involvement Cat Avg % - Small Arms', data[i]['Product Involvement Cat Avg % - Small Arms']],
                ['Product Involvement % - Thermal Coal', data[i]['Product Involvement % - Thermal Coal']],
                ['Product Involvement # of Holdings - Thermal Coal', data[i]['Product Involvement # of Holdings - Thermal Coal']],
                ['Product Involvement Cat Avg % - Thermal Coal', data[i]['Product Involvement Cat Avg % - Thermal Coal']],
                ['Product Involvement % - Tobacco', data[i]['Product Involvement % - Tobacco']],
                ['Product Involvement # of Holdings - Tobacco', data[i]['Product Involvement # of Holdings - Tobacco']],
                ['Product Involvement Cat Avg % - Tobacco', data[i]['Product Involvement Cat Avg % - Tobacco']],
                ['Carbon Date', data[i]['Carbon Date']],
                ['Percent AUM Covered - Carbon', data[i]['Percent AUM Covered - Carbon']],
                ['Low Carbon Designation', data[i]['Low Carbon Designation']],
                ['Carbon Risk Score', data[i]['Carbon Risk Score']],
                ['Carbon Risk Score Percent Rank in Category', data[i]['Carbon Risk Score Percent Rank in Category']],
                ['Carbon Risk Score Category Average', data[i]['Carbon Risk Score Category Average']],
                ['Benchmark Carbon Risk Score', data[i]['Benchmark Carbon Risk Score']],
                ['12 Month Average Carbon Risk Score', data[i]['12 Month Average Carbon Risk Score']],
                ['12 Month Average Carbon Risk Category Average', data[i]['12 Month Average Carbon Risk Category Average']],
                ['12 Month Average Carbon Risk Percent Rank in Category', data[i]['12 Month Average Carbon Risk Percent Rank in Category']],
                ['Carbon Exposure Score', data[i]['Carbon Exposure Score']],
                ['Carbon Exposure Score Category Average', data[i]['Carbon Exposure Score Category Average']],
                ['Carbon Management Score', data[i]['Carbon Management Score']],
                ['Carbon Management Score Category Average', data[i]['Carbon Management Score Category Average']],
                ['Carbon Operations Risk', data[i]['Carbon Operations Risk']],
                ['Carbon Operations Risk Category Average', data[i]['Carbon Operations Risk Category Average']],
                ['Carbon Products & Services Risk', data[i]['Carbon Products & Services Risk']],
                ['Carbon Products & Services Risk Category Average', data[i]['Carbon Products & Services Risk Category Average']],
                ['Stranded Assets Risk', data[i]['Stranded Assets Risk']],
                ['Stranded Assets Risk Category Average', data[i]['Stranded Assets Risk Category Average']],
                ['Carbon Intensity', data[i]['Carbon Intensity']],
                ['Carbon Intensity Category Average', data[i]['Carbon Intensity Category Average']],
                ['Fossil Fuel Involvement', data[i]['Fossil Fuel Involvement']],
                ['12 Month Average Fossil Fuel Exposure', data[i]['12 Month Average Fossil Fuel Exposure']],
                ['Fossil Fuel Category Average', data[i]['Fossil Fuel Category Average']],
                ['Thermal Coal Power Generation Involvement', data[i]['Thermal Coal Power Generation Involvement']],
                ['Thermal Coal Power Generation Category Average', data[i]['Thermal Coal Power Generation Category Average']],
                ['Thermal Coal Extraction Involvement', data[i]['Thermal Coal Extraction Involvement']],
                ['Thermal Coal Extraction Category Average', data[i]['Thermal Coal Extraction Category Average']],
                ['Oil Sands Extraction Involvement', data[i]['Oil Sands Extraction Involvement']],
                ['Oil Sands Extraction Category Average', data[i]['Oil Sands Extraction Category Average']],
                ['Arctic Oil & Gas Exploration Involvement', data[i]['Arctic Oil & Gas Exploration Involvement']],
                ['Arctic Oil & Gas Exploration Category Average', data[i]['Arctic Oil & Gas Exploration Category Average']],
                ['Carbon Solutions Involvement', data[i]['Carbon Solutions Involvement']],
                ['Carbon Solutions Category Average', data[i]['Carbon Solutions Category Average']],
                ['Renewable Energy Production Involvement', data[i]['Renewable Energy Production Involvement']],
                ['Renewable Energy Production Category Average', data[i]['Renewable Energy Production Category Average']],
                ['Renewable Energy Supporting Products & Services Involvement', data[i]['Renewable Energy Supporting Products & Services Involvement']],
                ['Renewable Energy Supporting Products & Services Category Average', data[i]['Renewable Energy Supporting Products & Services Category Average']],
                ['Green Transportation Involvement', data[i]['Green Transportation Involvement']],
                ['Green Transportation Category Average', data[i]['Green Transportation Category Average']],
                ['Oil & Gas Generation Involvement', data[i]['Oil & Gas Generation Involvement']],
                ['Oil & Gas Generation Category Average', data[i]['Oil & Gas Generation Category Average']],
                ['Oil & Gas Production Involvement', data[i]['Oil & Gas Production Involvement']],
                ['Oil & Gas Production Category Average', data[i]['Oil & Gas Production Category Average']],
                ['Oil & Gas Products & Service Involvement', data[i]['Oil & Gas Products & Service Involvement']],
                ['Oil & Gas Products & Services Category Average', data[i]['Oil & Gas Products & Services Category Average']],
                ['Carbon Risk Score All Funds Rank', data[i]['Carbon Risk Score All Funds Rank']],
                ['Carbon Risk Classification', data[i]['Carbon Risk Classification']],
                ['Percent of AUM with Negligible Carbon Risk', data[i]['Percent of AUM with Negligible Carbon Risk']],
                ['Percent of AUM with Low Carbon Risk', data[i]['Percent of AUM with Low Carbon Risk']],
                ['Percent of AUM with Medium Carbon Risk', data[i]['Percent of AUM with Medium Carbon Risk']],
                ['Percent of AUM with High Carbon Risk', data[i]['Percent of AUM with High Carbon Risk']],
                ['Percent of AUM with Severe Carbon Risk', data[i]['Percent of AUM with Severe Carbon Risk']],
                ['Carbon Exposure Score Percent Rank in Category', data[i]['Carbon Exposure Score Percent Rank in Category']],
                ['Carbon Management Score Percent Rank in Category', data[i]['Carbon Management Score Percent Rank in Category']],
                ['Carbon Operations Risk Percent Rank in Category', data[i]['Carbon Operations Risk Percent Rank in Category']],
                ['Carbon Products & Services Risk Percent Rank in Category', data[i]['Carbon Products & Services Risk Percent Rank in Category']],
                ['Stranded Assets Risk Percent Rank in Category', data[i]['Stranded Assets Risk Percent Rank in Category']],
                ['Carbon Intensity Percent Rank in Category', data[i]['Carbon Intensity Percent Rank in Category']],
                ['Highest Carbon Risk Score Category', data[i]['Highest Carbon Risk Score Category']],
                ['Lowest Carbon Risk Score Category', data[i]['Lowest Carbon Risk Score Category']],
                ['Highest Fossil Fuel Category', data[i]['Highest Fossil Fuel Category']],
                ['Lowest Fossil Fuel Category', data[i]['Lowest Fossil Fuel Category']],
                ['12 Month Average Fossil Fuel Category Average', data[i]['12 Month Average Fossil Fuel Category Average']],
                ['12 Month Average Highest Carbon Risk Score Category', data[i]['12 Month Average Highest Carbon Risk Score Category']],
                ['12 Month Average Lowest Carbon Risk Score Category', data[i]['12 Month Average Lowest Carbon Risk Score Category']],
                ['12 Month Average Highest Fossil Fuel Involvement Category', data[i]['12 Month Average Highest Fossil Fuel Involvement Category']],
                ['12 Month Average Lowest Fossil Fuel Involvement Category', data[i]['12 Month Average Lowest Fossil Fuel Involvement Category']],
                ['Sustainable Investment - Overall', data[i]['Sustainable Investment - Overall']],
                ['Sustainable Investment - ESG Fund Overall', data[i]['Sustainable Investment - ESG Fund Overall']],
                ['Sustainable Investment - ESG Incorporation', data[i]['Sustainable Investment - ESG Incorporation']],
                ['Sustainable Investment - ESG Engagement', data[i]['Sustainable Investment - ESG Engagement']],
                ['Sustainable Investment - Impact Fund Overall', data[i]['Sustainable Investment - Impact Fund Overall']],
                ['Sustainable Investment - Gender & Diversity', data[i]['Sustainable Investment - Gender & Diversity']],
                ['Sustainable Investment - Low Carbon/Fossil-Fuel Free', data[i]['Sustainable Investment - Low Carbon/Fossil-Fuel Free']],
                ['Sustainable Investment - Community Development', data[i]['Sustainable Investment - Community Development']],
                ['Sustainable Investment - Environmental', data[i]['Sustainable Investment - Environmental']],
                ['Sustainable Investment - Other Impact Themes', data[i]['Sustainable Investment - Other Impact Themes']],
                ['Sustainable Investment - Environmental Sector Overall', data[i]['Sustainable Investment - Environmental Sector Overall']],
                ['Sustainable Investment - Renewable Energy', data[i]['Sustainable Investment - Renewable Energy']],
                ['Sustainable Investment - Water-Focused', data[i]['Sustainable Investment - Water-Focused']],
                ['Sustainable Investment - General Environmental Sector', data[i]['Sustainable Investment - General Environmental Sector']],
                ['Employs Exclusions - Overall', data[i]['Employs Exclusions - Overall']],
                ['Employs Exclusions - Uses Norms-Based Screening', data[i]['Employs Exclusions - Uses Norms-Based Screening']],
                ['Employs Exclusions - Abortion/Stem Cells', data[i]['Employs Exclusions - Abortion/Stem Cells']],
                ['Employs Exclusions - Adult Entertainment', data[i]['Employs Exclusions - Adult Entertainment']],
                ['Employs Exclusions - Alcohol', data[i]['Employs Exclusions - Alcohol']],
                ['Employs Exclusions - Animal Testing', data[i]['Employs Exclusions - Animal Testing']],
                ['Employs Exclusions - Controversial Weapons', data[i]['Employs Exclusions - Controversial Weapons']],
                ['Employs Exclusions - Fur & Specialty Leather', data[i]['Employs Exclusions - Fur & Specialty Leather']],
                ['Employs Exclusions - Gambling', data[i]['Employs Exclusions - Gambling']],
                ['Employs Exclusions - GMOs', data[i]['Employs Exclusions - GMOs']],
                ['Employs Exclusions - Military Contracting', data[i]['Employs Exclusions - Military Contracting']],
                ['Employs Exclusions - Nuclear', data[i]['Employs Exclusions - Nuclear']],
                ['Employs Exclusions - Palm Oil', data[i]['Employs Exclusions - Palm Oil']],
                ['Employs Exclusions - Pesticides', data[i]['Employs Exclusions - Pesticides']],
                ['Employs Exclusions - Small Arms', data[i]['Employs Exclusions - Small Arms']],
                ['Employs Exclusions - Thermal Coal', data[i]['Employs Exclusions - Thermal Coal']],
                ['Employs Exclusions - Tobacco', data[i]['Employs Exclusions - Tobacco']],
                ['Employs Exclusions - Other', data[i]['Employs Exclusions - Other']],
                ['Historical Sustainability Score Global Category Average', data[i]['Historical Sustainability Score Global Category Average']],
                ['Historical Sustainability Percent Rank in Global Category', data[i]['Historical Sustainability Percent Rank in Global Category']],
                ['Historical Sustainability Absolute Rank in Global Category', data[i]['Historical Sustainability Absolute Rank in Global Category']],
                ['Portfolio ESG Risk Exposure Score', data[i]['Portfolio ESG Risk Exposure Score']],
                ['Portfolio ESG Managed Risk Score', data[i]['Portfolio ESG Managed Risk Score']],
                ['Percent of AUM with NULL ESG Risk Scores', data[i]['Percent of AUM with NULL ESG Risk Scores']],
                ['Percent of AUM with High & Severe Controversies', data[i]['Percent of AUM with High & Severe Controversies']],
                ['Percent of AUM with No Controversies', data[i]['Percent of AUM with No Controversies']],
                ['Percent of AUM with Low Controveries', data[i]['Percent of AUM with Low Controveries']],
                ['Percent of AUM with Moderate Controversies', data[i]['Percent of AUM with Moderate Controversies']],
                ['Percent of AUM with Significant Controversies', data[i]['Percent of AUM with Significant Controversies']],
                ['Percent of AUM with High Controversies', data[i]['Percent of AUM with High Controversies']],
                ['Percent of AUM with Severe Controversies', data[i]['Percent of AUM with Severe Controversies']]
            ]);
            //console.log(criteria);
            const yolo : Map<String, String> = new Map<String, String>([
                ["type","product"],
                ["isin_code", 'unknown'],
                ["product_name", data[i]['Name']],
                ["category", data[i]['Global Category']],
                ["criteria", criteria]
            ]);
            products_list.push({ index: { _index: 'scala', _type: 'database'}});
            products_list.push(this.mapToObj(yolo));
        }

        //console.log(products_list);

/*       ELASTIC_CLIENT.bulk({
            index: 'scala',
            type: 'database',
            body: products_list
        }, (err, response) => {
            if (err){
                console.log("ERROR: ", err);
            }
            else {
                console.log("RESPONSE: ", response)
            }
        });*/


    }
}
